version: '3'

services:
  db:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_DB: "bot"
      POSTGRES_USER: "bot_user"
      POSTGRES_PASSWORD: "bot_password"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


volumes:
  pgdbdata: null