version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
     - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/src/
    
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    expose:
      - 3000
    env_file:
      - ./.env
    volumes:
      - ./frontend:/src/
      - node_modules:/src/node_modules/

volumes:
  node_modules: null
