version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
     - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/src/
  