databases:
  - name: telegram-bot
    databaseName: bot
    user: bot_user

services:
  - type: web
    name: frontend
    runtime: node
    plan: free
    buildCommand: "npm build ./frontend"
    startCommand: "npm start ./frontend"
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: 'backend'
          type: web
          property: hostport
    
  - type: web
    name: backend
    runtime: python
    plan: free
    buildCommand: "cd ./backend && poetry install"
    startCommand: "cd ./backend && uvicorn run 'backend.app:app --host 0.0.0.0 --port 8000'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot
          property: connectionString
      - key: WEBAPP_URL
        fromService:
          name: frontend
          type: web
          property: hostport
      - key: BOT_TOKEN
        sync: false
      - key: CORS_ORIGINS
        fromService:
          name: 'frontend'
          type: web
          property: hostport
    

